#!/bin/bash

if [ $# -gt 1 ] || [ $# -eq 0 ]; then
  echo 'Usage: adwhirl [start|daemon|stop]'
  echo '    start  - Starts AdWhirl Invoker'
  echo '    daemon - Starts AdWhirl Daemon'
  echo '    stop   - Stops all AdWhirl Services'
  exit 1
fi

command=$1

if [ ${command} = 'start' ]; then
  # attempt to restart/start 1 time
  cnt=0
  while [ $cnt -lt 1 ];
  do
    for pid in `ps auxww | grep java | grep -i adwhirl.jar | grep -i Invoker | grep -v Daemon | awk '{print $2}'`; do
      #use SIGINT so we can cleanup  
      sudo kill -2 $pid

      sleep 15

      sudo kill -9 $pid
    done

    java -Xms256m -Xmx1024m -cp dist/adwhirl.jar Invoker >Invoker.log 2>Invoker.err &

    sleep 30
    
    echo "^]quit" | telnet localhost 80 1>/dev/null 2>/dev/null

    if [ $? -eq 0 ];
    then
      break
    fi

    let cnt=cnt+1
  done

elif [ ${command} = 'daemon' ]; then
  # attempt to restart/start 1 time
  cnt=0
  while [ $cnt -lt 1 ];
  do
    for pid in `ps auxww | grep java | grep -i adwhirl.jar | grep -i Daemon | grep -v Invoker | awk '{print $2}'`; do
      #use SIGINT so we can cleanup  
      sudo kill -2 $pid
    done

    sleep 15

    java -cp dist/adwhirl.jar Daemon >Daemon.log 2>Daemon.err &

    sleep 15
    
    for pid in `ps auxww | grep java | grep -i adwhirl.jar | grep -i Daemon | grep -v Invoker | awk '{print $2}'`; do
	break
    done

    let cnt=cnt+1
  done

elif [ ${command} = 'stop' ]; then
  for pid in `ps auxww | grep java | grep -i adwhirl.jar | awk '{print $2}'`; do
    #use SIGINT so we can cleanup  
    sudo kill -2 $pid
  done

else
  echo 'Usage: adwhirl [start|daemon|stop]'
  echo '    start  - Starts AdWhirl Invoker'
  echo '    daemon - Starts AdWhirl Daemon'
  echo '    stop   - Stops all AdWhirl Services'
  exit 1

fi

exit 0
